# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Serenity Automation CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: '114.0.5735.90'

      - name: Run Serenity Tests
        run: mvn verify -Dwebdriver.driver=chrome -Dchrome.options="--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-allow-origins=*" -Dserenity.logging=DEBUG


      - name: Publish Serenity Reports
        if: success()
        run: |
          mkdir -p serenity-report
          cp -r target/site/serenity/* serenity-report/

      - name: Upload Serenity Reports as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: serenity-report
          path: serenity-report

      - name: Notify CI/CD Success
        if: success()
        run: echo "CI/CD Pipeline completed successfully."

      - name: Notify CI/CD Failure
        if: failure()
        run: echo "CI/CD Pipeline failed."
