# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Serenity Automation CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxss1 \
            libappindicator3-1 \
            libindicator7 \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            xdg-utils \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxrandr2 \
            libxi6 \
            libxtst6 \
            libxss1 \
            libxshmfence1 \
            libgbm-dev \
            libasound2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable' # or specify a specific stable version if needed

      - name: Check ChromeDriver Version
        id: check_chromedriver
        run: |
          CHROMEDRIVER_PATH=$(which chromedriver)
          if [ -z "$CHROMEDRIVER_PATH" ]; then
            echo "ChromeDriver is not installed."
            exit 1
          else
            echo "ChromeDriver is installed at: $CHROMEDRIVER_PATH"
            echo "CHROMEDRIVER_PATH=$CHROMEDRIVER_PATH" >> $GITHUB_ENV
            chromedriver --version
          fi

      - name: Run Serenity Tests
        env:  # Set the environment variable for this step
          CHROMEDRIVER_PATH: ${{ env.CHROMEDRIVER_PATH }}
        run: mvn verify -Dwebdriver.chrome.driver=$CHROMEDRIVER_PATH 

      - name: Publish Serenity Reports
        if: success()
        run: |
          mkdir -p serenity-report
          cp -r target/site/serenity/* serenity-report/

      - name: Upload Serenity Reports as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: serenity-report
          path: serenity-report

      - name: Notify CI/CD Success
        if: success()
        run: echo "CI/CD Pipeline completed successfully."

      - name: Notify CI/CD Failure
        if: failure()
        run: echo "CI/CD Pipeline failed."
