name: Serenity Automation CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: '0 4 * * *' 
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxss1 \
            libappindicator3-1 \
            libindicator7 \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            xdg-utils \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxrandr2 \
            libxi6 \
            libxtst6 \
            libxss1 \
            libxshmfence1 \
            libgbm-dev \
            libasound2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: temurin

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Update Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version
          # Use WebDriverManager to ensure the ChromeDriver version matches
          mvn dependency:resolve -Dwebdriver.chrome.driver=latest

      - name: Update WebDriverManager
        run: mvn dependency:resolve -Dwebdriver.chrome.driver=latest


      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Run Tests with Xvfb
        env:
          WEBDRIVER_CHROME_LOG_LEVEL: ALL
        run: |
          Xvfb :99 &  # Start Xvfb on display 99
          export DISPLAY=:99  # Set display environment variable
          echo "Running Serenity Tests..."
          mvn test -Dwebdriver.chrome.args="--headless --disable-gpu --no-sandbox --disable-dev-shm-usage --remote-allow-origins=*"

      - name: Try getting the reports
        run: mvn clean verify

      - name: Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Serenity Report                 
          path: target/site/serenity/ 

      - name: Upload Chrome Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: chrome-logs
          path: chrome.log

      - name: Notify CI/CD Success
        if: success()
        run: echo "CI/CD Pipeline completed successfully."

      - name: Notify CI/CD Failure
        if: failure()
        run: echo "CI/CD Pipeline failed."
